### ISSUE TITLE
Cannot read property 'constructor' of undefined

### ISSUE THREAD

**Issue by DejanVuj** [sweetalert2/ngx-sweetalert2#101]
I get this error once I install it on angular version 7. Anyone have some idea what could be the issue? I can't use it at all.

**Comment by AnisAli** [comment]
change "sweetalert2": "^8.0.0" to  "sweetalert2": "^7.26.9" in package.json file

**Comment by limonte** [comment]
Thanks for reporting, @DejanVuj  

I would expect npm to be smarter and to install sweetalert2@7 because it's in `peerDependencies` of `ngx-sweetalert2`, but no:

![image](https://user-images.githubusercontent.com/6059356/51437716-8ac9a680-1caa-11e9-8af8-68b95b2bd94a.png)

I will update the installation instructions accordingly:

```diff
- npm i sweetalert2 @toverux/ngx-sweetalert2
+ npm i sweetalert2@7 @toverux/ngx-sweetalert2
```

**Comment by limonte** [comment]
Good news!

The new version has been released: https://github.com/sweetalert2/ngx-sweetalert2/releases/tag/v5.0.0

It supports Angular 7 and SweetAlert2 v8

Please pay attention that the package name has been changed to `@sweetalert2/ngx-sweetalert2`,  update your `package.json` accordingly:

```diff
-  "sweetalert2": "^7.0.0",
-  "@toverux/ngx-sweetalert2": "^4.0.0",
+  "sweetalert2": "^8.0.0",
+  "@sweetalert2/ngx-sweetalert2": "^5.0.0",
```
