### ISSUE TITLE
SwalComponent with preconfirm and showValidationMessage does not work

### ISSUE THREAD

**Issue by Franki1986** [sweetalert2/ngx-sweetalert2#119]
I have made a small example with a swal component.
If I call the showValidationMessage in the preconfirm it does not show.

[ShowValidationMessage](https://stackblitz.com/edit/angular-d3k6hs?file=src%2Fapp%2Fapp.component.ts)

**Comment by Franki1986** [comment]
Close with this eaxample: 
[ShowValidationMessage](https://stackblitz.com/edit/angular-d3k6hs?file=src%2Fapp%2Fapp.component.ts)

**Comment by Franki1986** [comment]
I have to reopen this! If the swal component has content this does not work!
[show validation message if swal component has content](https://stackblitz.com/edit/angular-vc9v9s?file=src/app/app.component.html)

**Comment by Franki1986** [comment]
Any news?

**Comment by toverux** [comment]
Sorry for not answering this.
This is by design. The content target used to replace the whole content element from the native SweetAlert2, therefore the validation message block was removed from the DOM.
Instead you can use your own target, you don't have to only use the ones provided by `SwalPartialTargets`.

The current content target is:

```ts
public readonly content = () => Swal.getContent();
```

To avoid erasing all the elements contained in the swal's content, including the validation message block, declare your own function in your component:

```
public readonly content = () => Swal.getContent().querySelector('#swal2-content');
```

And then use it like this:

```html
<swal>
    <ng-container *swalPartial="content"></ng-container>
</swal>
```

The next version of ngx-sweetalert2 will address this issue and provide the latter one by default.
