### ISSUE TITLE
Swal dialog disappearing after router.navigate

### ISSUE THREAD

**Issue by jancoow** [sweetalert2/ngx-sweetalert2#120]
Hi.

When using swal as angular component, the swal dialog disappears after route change  Is there an option to prevent this? 

HTML:
``` html
<swal
  #deleteSwal
  title="Delete"
  text="This cannot be undone"
  type="question"
  i18n-title
  i18n-text
>
</swal>
```

Component:
``` js
class MyComponent {
  @ViewChild('deleteSwal') private deleteSwal: SwalComponent;

  constructor(public router: Router) {
        this.deleteSwal.open.subscribe(r => {
            this.router.navigate(["/"]);
        });
        deleteSwal();
  }
}
```

I guess this is happening because the Angular component gets destroyed on route change. It works fine when using the fire() method from Swal itself: The Swal dialog stays visible on the next page. 

``` js
 Swal.fire("test");
 this.router.navigate(["/"]);
```

**Comment by toverux** [comment]
Hello @jancoow,

Yes, this happens because the component is destroyed. However, this is by design, I _could_ have done it differently. I assumed that in most cases, you want the dialog to disappear when its controller component is destroyed.
I even implemented this behaviour after noticing that the dialog stayed open when chaning routes... and I didn't wanted that :D

It would be possible to implement an option so the dialog stays open no matter what. In the meantime I recommend you to stick with the native SweetAlert API if that is a blocking problem for you.

**Comment by jancoow** [comment]
It would be awesome if there is an option for this behavior! Maybe an extra option closeOnDestroy=true/false . 

I'm currently rewriting my whole application to the Angular component instead of the native Sweet Alert API so I can use i18n translations for title and text. I stumbled on this issue for a few alerts while rewriting it.

**Comment by toverux** [comment]
I agree that it would be nice to have, thanks for your feedback. I'll implement that.

**Comment by toverux** [comment]
Hello there!

I may be months late, but I resolved my promise (bad pun intended).

You can now disable automatic dismissal on component destroy by passing this option:

```ts
SweetAlert2Module.forRoot({
    dismissOnDestroy: false
})
```

Or, you can disable this behaviour on a precise `<swal>` components if you want to keep the normal behaviour at the module level:

```html
<swal [swalDismissOnDestroy]="false"></swal>
```
