### ISSUE TITLE
Error when import in module angular 7

### ISSUE THREAD

**Issue by charry0821** [sweetalert2/ngx-sweetalert2#131]
I have the next problem when i try to import the ngx-sweetalert2 in the app.module. This error launch when i try to compile the project. I do the import as it is in the official documentation

WARNING in ./node_modules/@sweetalert2/ngx-sweetalert2/fesm5/sweetalert2-ngx-sweetalert2.js 1227:59-77
"export 'ɵɵdefineInjectable' was not found in '@angular/core'

Thanks for the help.

**Comment by toverux** [comment]
What version of Angular do you use?

**Comment by charry0821** [comment]
i'm using angular 7.3

**Comment by toverux** [comment]
Ok, it seems that AoT metadata produced by Angular 8 aren't compatible with Angular 7 (after all, that's a breaking release). If you can upgrade Angular, do it, otherwise, please use ngx-sweetalert v5.x instead. The API is pretty much the same. [Here is the Readme for version 5.1.0](https://github.com/sweetalert2/ngx-sweetalert2/tree/v5.1.0)
