### ISSUE TITLE
Set up CI

### ISSUE THREAD

**Issue by limonte** [sweetalert2/ngx-sweetalert2#139]
@toverux I just noticed that CI tests were disabled in https://github.com/sweetalert2/ngx-sweetalert2/commit/bf91a7e805e45ce526a57fd5489463159a8c5442

I just added the simple config for GitHub Actions, but something isn't right. Could you please help me with setting up testing and releasing from CI? Thanks in advance!

PS. congrats on 400 stars! :muscle:

**Comment by toverux** [comment]
For the tests, Chrome doesn't starts because there's no X display available, I already stumbled upon that on Travis back in the days.
But now there are headless Chromes so maybe there's some command line option missing. In the worst case scenario, I'll continue to check tests manually before pushing.
I'll have a look the next time I'm releasing a version.
Closing the issue since CI does most of the job I would expect from it now.

**Comment by limonte** [comment]
> For the tests, Chrome doesn't starts because there's no X display available

For some reason, tests are failing for me locally as well, steps:

```sh
yarn build
yarn test
```

Result: 

![image](https://user-images.githubusercontent.com/6059356/68527130-4caa7b80-02ec-11ea-9caa-08adb73d24f1.png)

**Comment by limonte** [comment]
@toverux if you can figure out how to fix tests, I can figure out how to run them in CI

**Comment by limonte** [comment]
> @toverux if you can figure out how to fix tests, I can figure out how to run them in CI

In fact, the second part is as easy as #141
