### ISSUE TITLE
customCSS not being applied 

### ISSUE THREAD

**Issue by Firetrip** [sweetalert2/ngx-sweetalert2#153]
So our setup is an angular 9 application. 
if you open a sweetalert within a component, i would expect that local css styles are enough to apply them.

component.ts
```
.....
customClass: {
        container: 'sw-component',
}
```

component.css
```
.sw-component {
    background-color: red;
}

```
However styles are not being applied. Only way I discovered for now is to place the class `sw-component` within the index.html or somewhere at root-level. 
This seems not like expected behaviour 😢

**Comment by toverux** [comment]
It is expected behaviour. Unfortunately, I can't do anything about it in the library. The reason is that Angular parses your HTML and CSS and rewrites them by adding prefixes to your classes, in order to provide [style encapsulation](https://angular.io/api/core/ViewEncapsulation).
We have no way to tell Angular "hey, those strings are component-level CSS classes, please compile them accordingly".

You would have to use `ViewEncapsulation.None` to keep those CSS classes in your component (then Angular won't prefix your classes), but you may not want to disable view encapsulation just for that. If you don't, the correct way is to put the custom classes in a global CSS file, generally `styles.css` with a default Angular CLI installation.

You can also create a new CSS file aside styles.css (ex. sweetalert2-theme.css) and import it in your `styles` array in `angular.json`.

**Comment by Firetrip** [comment]
Thanks!
