### ISSUE TITLE
Add SweetAlert2 v10 support (new deny button)

### ISSUE THREAD

**Issue by limonte** [sweetalert2/ngx-sweetalert2#173]
Seems there's nothing breaking for the Angular integration, I'll just add the new properties as inputs and the new deny button as a portal target in ngx-sweetalert2 soon.

_Originally posted by @toverux in https://github.com/sweetalert2/sweetalert2/issues/2043#issuecomment-688723602_

**Comment by toverux** [comment]
Hi @limonte,

Sorry for the delay, but it's coming very soon now as I've done most of the work this evening =)

I'd have liked to have your opinion, too, about my `@Output` that is currently named `cancel`. It is used like that: `<swal (cancel)="handleCancellation($event /* aka dismiss reason */)">`.

In modern SweetAlert2 terminology though, **"cancel"** is more about the button itself, and **"dismiss"** really defines the "disapperance of the modal caused by various events _including_ a click on the cancel button", and `(cancel)` is used for the latter.

So, I was thinking about renaming `(cancel)` to `(dismiss)` to better match the philosophy of SweetAlert2. Given that I will also have `(confirm)` and `(deny)`, this set of outputs will be aligned on the `SweetAlertResult` structure. No surprises.

However, I have a `dismiss()` method that calls `Swal.close()`, and I can't have both `(dismiss)` and `dismiss()`. I can't simply rename `dismiss()` into `close()` though because then it would collide with another older output, `(close)`, that exposes the `onClose` hook...

So how should I call `dismiss()` ?
I don't want to rename `(close)` (and the other hooks) into `(onClose)` or `(closed)` because that would be against the framework conventions.

**Comment by limonte** [comment]
Hm, I don't have any good opinion about the naming now. I'll think about it. Also @zenflow might have a good idea.

**Comment by limonte** [comment]
@toverux sorry to bother you, Morgan! Just a reminder about this issue, no pressure, only when you have time. Thank you!

**Comment by toverux** [comment]
Hi, no worries, I was indeed quite busy, but now I'm on vacations and I'll be able to look at it again very soon!

**Comment by timeimp** [comment]
Hi @toverux!

I wanted to check if the Deny button was released recently?

Cheers,
timeimp

**Comment by jarkym** [comment]
Hello @toverux ,

Angular version 11 is here. Hope to see an update in angular core and feature versions specially the Deny button.

best regards,
R-jay

**Comment by toverux** [comment]
https://github.com/sweetalert2/ngx-sweetalert2/releases/tag/v9.0.0 brings SweetAlert2 v10 and Angular v11 support :tada:

**Comment by limonte** [comment]
Amazing work @toverux! The release notes are 😍 

Thank you for being the maintainer of this project!

**Comment by toverux** [comment]
Just amended the release notes to talk about the features too, and not just the breaking changes ;)
