### ISSUE TITLE
using (confirm) inside ngFor ?

### ISSUE THREAD

**Issue by kudsyf** [sweetalert2/ngx-sweetalert2#40]
am using the confim alert as below

```html
<li class="list-group-item row mb-0" *ngFor="let l of myarray">
    <div class="col-md-5">{{l.a}}</div>
    <div class="col-md-5">{{l.b}}</div>
    <div class="col-md-2">
        <i class="fa fa-trash fa-lg" [swal]="delete" (confirm)="delete(l)"></i>
    </div>
</li>

<swal #delete title="Are you sure you want to delete?" text="This cannot be undone" type="question"  [showCancelButton]="true" [focusCancel]="true"></swal>
```

and the delete() method remove the selected element from the array .. but when i use this code .. the (confirm) runs on all array elements and delete them one by one !!? its like the confirm called more than once !!?

**Comment by toverux** [comment]
Hello @kudsyf, interesting issue. I'd be happy to reproduce, but:

 - You don't show where the closing `</li>` is, so I don't know if the `<swal>` is comprised in the *ngFor here. Can you fix your code sample?
 - A potential problem I see: You have a `delete()` function in your TypeScript, but your swal is also named `delete`. There's probably a conflict here. Try to name your `<swal>` "`deleteSwal`" or something like that first.

**Comment by toverux** [comment]
Hello again,

After reading this issue again, I immediately understood what's the problem. The thing is that each `[swal]` will subscribe to confirm/cancel events of the _same_ `<swal>` instance. So the behaviour you've encountered make perfect sense. Each entry will subscribe to the same modal and all of them will receive the same confirm/cancel events.

This is logical but definitely not practical. I've released a new version where multiple `[swal]` directives are now maintaining a "mutex" subscription to the shared `<swal>` instance. This will give the expected behaviour.

Please upgrade you ngx-sweetalert2 version:

----

<a name="3.3.1"></a>
## [3.3.1](https://github.com/sweetalert2/ngx-sweetalert2/compare/v3.3.0...v3.3.1) (2018-02-14)


### Bug Fixes

* **SwalDirective:** SwalDirectives now do a "cooperative mutex" when subscribing to an existing SwalComponent instance ([#40](https://github.com/sweetalert2/ngx-sweetalert2/issues/40)) ([19bc9c3](https://github.com/sweetalert2/ngx-sweetalert2/commit/19bc9c3))
