### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by zenflow** [sweetalert2/ngx-sweetalert2#47]
> Main features [of semantic-release]: [...] Generates a changelog and creates a GitHub release https://github.com/sweetalert2/sweetalert2/issues/511#issue-223364031

Do you have this disabled on this project? Could you show us what it looks like?

**Comment by toverux** [comment]
Yes, the last one for example: https://github.com/sweetalert2/ngx-sweetalert2/releases/tag/v3.1.0
Just added by hand the "Angular 5" section and the first paragraph.

Previous ones were mostly done by hand because semantic-release 9.x occasionally failed to publish it. But they have published a lot of major versions now, reviewing the architecture, and it seems to work much better (also, previous version weren't logging anything so failure were hard to debug).

Another example: https://github.com/jaebradley/semantic-release-example/releases

The type of commit (feat, fix) make sections, breaking changes are put into their own sections, trivial (chore, refactor) commits aren't shown. The scope (`feat(SCOPE)`) of the commit is in bold. 
It adds a link to the commit, a title with a link to the diff comparison between the first and latest commit of the release, an HTML anchor and the date (GitHub also puts a title and a date, but semantic-release isn't GitHub-specific).

**Comment by zenflow** [comment]
@toverux Sorry for the delayed response.. Would it be pretty easy to have a CHANGELOG.md file that is automatically updated? (asking for the core repo, not necessarily this one)

**Comment by toverux** [comment]
Sorry, thought that it was your only question :)

Yes, it seems possible. Although the default setup publishes the release notes in GitHub Releases using [@semantic-release/release-notes-generator](https://github.com/semantic-release/release-notes-generator), this other plugin (not in the "semantic starter pack") maintains the CHANGELOG.md file : [@semantic-release/changelog](https://github.com/semantic-release/changelog).

But we may need [@semantic-release/git](https://github.com/semantic-release/git) with it to publish the CHANGELOG.md on Git. Unless maybe we'd modify it locally before committing? Needs investigation.

So, never tried it but it should be quite easy to setup a few custom semantic-release steps in the workflow without relying on it for everything (but not as easy as `$ semantic-release-cli setup` though :smile:).
