### ISSUE TITLE
[Question] Handling async/await or how to properly create a reusable swal

### ISSUE THREAD

**Issue by ryanbuening** [sweetalert2/ngx-sweetalert2#52]
Sorry in advance if this is a question more suited for Stack Overflow, but there is not a tag for `ngx-sweetalert2`. I can move this if needed.

I have a `swal.service.ts` file with the following:

```
import { Injectable } from '@angular/core';
import swal from 'sweetalert2';

@Injectable()
export class SwalService {
    public showSwal() {
        swal({
            title: 'Are you sure?',
            text: 'You will not be able to recover this imaginary file!',
            type: 'warning',
            showCancelButton: true,
            confirmButtonText: 'Yes, delete it!',
            cancelButtonText: 'No, keep it'
        }).then((result) => {
            if (result.value) {
                swal(
                    'Deleted!',
                    'Your imaginary file has been deleted.',
                    'success'
                );
                return true; // is there a way I can return what option was chosen back to the component.ts?
            }
            // else if (result.dismiss === swal.DismissReason.cancel) { // DismissReason doesn't exist on swal??
            //     swal(
            //         'Cancelled',
            //         'Your imaginary file is safe :)',
            //         'error'
            //     );
            // }
        });
    }
}
```
and I call it from my `component.ts`:

```
const chosenBoolean = await this.swalService.showSwal();
console.log("chosenBoolean: " + chosenBoolean);
```

My await syntax is pseudo-code of what I'm trying to accomplish. Is there a way I can use async/await in this manner? Is there a different way to achieve this? My overall goal is to have reusable SweetAlert service that I call from different components and return what option/button the user clicked to the component and take various actions based upon what was selected.

**Comment by toverux** [comment]
It's indeed more suited to StackOverflow :) Not just because it's a "how to do this" question, but also because this has nothing to do with my library here. You are not using ngx-sweetalert2 here, at all.

But because I like to help and since I don't have too much issues to deal with, I can point you in the right direction:

`.then` is what you use to retrieve a Promise's result. That's basically what `await` does, in a more succint manner and more synchronous-looking way.

Therefore, you need to return the promise returned by SweetAlert2 to delegate the Promise resolution handling to the consumer code, so basically :

```ts
@Injectable()
export class SwalService {
    public showSwal(): Promise<any> {
        return swal({
            title: 'Are you sure?',
            text: 'You will not be able to recover this imaginary file!',
            type: 'warning',
            showCancelButton: true,
            confirmButtonText: 'Yes, delete it!',
            cancelButtonText: 'No, keep it'
        });
    }
}
```

Consuming code will look like :

```ts
const { value: userConfirms, dismiss } = await this.swalService.showSwal();

if (!dismiss && userConfirms) {
    // delete imaginary file here
}
```

If you need more informations, please ask your question on SO and please be more careful in the future when posting on GitHub (especially, please post the right repository) 😉

**Comment by ryanbuening** [comment]
Noted and thanks for clarifying.
