### ISSUE TITLE
Navigating to previous page keeps sweet alert open

### ISSUE THREAD

**Issue by brampeirs** [sweetalert2/ngx-sweetalert2#54]
The alert doen't close when navigating to a previous page (when using prev keys).

**Comment by toverux** [comment]
Hello @brampeirs, I think your problem may be fixed by the latest version (see below). Now, a currently-displayed SweetAlert will be closed if the `<swal>` component that created it is destroyed by Angular.
Please upgrade and tell me if you still have the problem (then I may need more informations / repro code).

----

<a name="3.3.0"></a>
# [3.3.0](https://github.com/sweetalert2/ngx-sweetalert2/compare/v3.2.1...v3.3.0) (2018-02-14)


### Features

* **SwalComponent:** close a sweet alert when the SwalComponent that created it is detroyed ([#54](https://github.com/sweetalert2/ngx-sweetalert2/issues/54)) ([2af800a](https://github.com/sweetalert2/ngx-sweetalert2/commit/2af800a))

**Comment by brampeirs** [comment]
Updating solved the problem, thank you.
