### ISSUE TITLE
version mismatch error

### ISSUE THREAD

**Issue by kemalatila** [sweetalert2/ngx-sweetalert2#63]
Hi,
I am taking this error. 

`ERROR in Metadata version mismatch for module /home/myuser/Code/crm/node_modules/@toverux/ngx-sweetalert2/toverux-ngx-sweetalert2.d.ts, found version 4, expected 3, resolving symbol CustomerRegisterModule in /home/myuser/Code/crm/src/app/pages/customer-register/customer-register.module.ts, resolving symbol CustomerRegisterModule in /home/myuser/Code/crm/src/app/pages/customer-register/customer-register.module.ts, resolving symbol CustomerRegisterModule in /home/myuser/Code/crm/src/app/pages/customer-register/customer-register.module.ts
`

What could be reason?

**Comment by mfkara** [comment]
I have a same issue . How can I solve?

**Comment by kemalatila** [comment]
probably one of your npm package in not compatible with your angular version

**Comment by idevthings** [comment]
changing the **key** _version_ to 3 in**@toverux/ngx-sweetalert2/toverux-ngx-sweetalert2.d.ts** file will solve the problem temporaly. 

I am still trying to figure it out where does it come from. My angular version in ^4.0.0.

I will update the project to ^5.0.0 and see if this solves the problem.

**Comment by toverux** [comment]
I assume you meant `toverux-ngx-sweetalert2.metadata.json` and not `toverux-ngx-sweetalert2.d.ts` ?

Because indeed, the metadata version is different from Angular's version. The latest version of the format is v.4 and I think it is generated by Angular 5 to 6. Angular 4 was probably writing/reading v.3 metadata.

Meaning that I involuntarily introduced a breaking change: the library was still compatible with Angular 4 but not its AoT metadata (generated with my Angular 5 dev dep). I recommend to people that are still on Angular 4 to find a version of the library that still has v.3 metadata.

**Comment by idevthings** [comment]
Yeah, the metadata file (edited). So updating to Angular 5 should solve this issue I assume.  Thx.

**Comment by toverux** [comment]
Yeah, seems pretty clear now.
I'll close this and recommend people to upgrade their Angular versions _or_ staying on an old build of ngx-sweetalert2, setting their dependency on `~3.0.1` (I'm really sorry for the unwanted breaking change, I'll be more careful on that).
