### ISSUE TITLE
swal closes automatically

### ISSUE THREAD

**Issue by cristianfloresee** [sweetalert2/ngx-sweetalert2#98]
swal closes automatically and to fix it I must set a setTimeout()

![hhh](https://user-images.githubusercontent.com/28737734/49680581-ab2fff80-fa74-11e8-884a-e491a811e670.gif)

```
export class AppComponent {

  @ViewChild('successSwal') private successSwal: SwalComponent;

  // Swal Option
  SWAL_DELETE = {
    title: '¿Está seguro?',
    type: 'warning',
    showCancelButton: true,
    cancelButtonText: 'Cancelar',
    focusCancel: true,
    reverseButtons: true,
    confirmButtonText: 'Si, eliminar',
    text: '¿seguro desea eliminar la pregunta?'
  };

  // Swal Option
  SWAL_SUCCESS_DELETE = {
    title: 'Acción realizada!',
    type: 'success',
    confirmButtonText: 'Aceptar',
    text: 'La pregunta ha sido eliminada'
  };

  // This works
  deleteQuestion() {
    this.successSwal.show();
  }

  // But this works correctly only with a settimeout
  /*
    deleteQuestion(id_question) {
        this._questionSrv.deleteQuestion(id_question)
           .subscribe(
              result => {
                this.getQuestions();
                setTimeout(() => {
                  this.successSwal.show();
                }, 100);
              },
              error => {
                 console.log("error:", error);
              });
    }
  */
}
```
```
<button [swal]="deleteSwal">Show Alert Confirmation</button>
<swal #deleteSwal (confirm)="deleteQuestion()" [options]="SWAL_DELETE"></swal>
<swal #successSwal [options]="SWAL_SUCCESS_DELETE"></swal>
```

my problem is commenting:
https://stackblitz.com/edit/angular-qag3s5

**Comment by toverux** [comment]
Hello @cristianfloresee,

Thanks for the StackBlitz.
I don't know how to reproduce the problem though, I don't quite understand how I could replicate it on StackBlitz. Could you edit it so it doesn't works?

That said, I think that your dynamic table may cause a problem.
Is your success swal declared _inside_ an item that is repeated with *ngFor? If so, that may be a/the problem, since ngx-sweetalert2 closes swals when their parent view is destroyed. Be careful about that.

To test that hypotesis, try declaring you success swal outside of the item that's being deleted.

**Comment by seiyria** [comment]
Yeah, my final solution was to call it all in the component instead of from the loop. I think it would help if the documentation had an example that addresses this because this could be a pretty big source of frustration if you aren't expecting it.
